# api/config/packages/vich_uploader.yaml

vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/src/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        csv_object:
            uri_prefix: /csv
            upload_destination: '%kernel.project_dir%/src/csv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer